stages:

  build_vector_store:
    cmd: python -m src.read_pdf
    deps:
    - src/read_pdf.py
    - data
    params:
    - read_pdf.chunk_size
    - read_pdf.chunk_overlap
    outs:
    - vector_db

  test_chatbot:
    cmd: python -m src.chat
    deps:
    - src/chat.py
    - vector_db
    - params.yaml
    params:
    - chat.temperature
    - chat.retrieval_k
    - chat.display_chunks
    outs:
    - output/chat_output.txt

params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
